name: build

env:
   CMAKE_BUILD_PARALLEL_LEVEL: 4
   CTEST_PARALLEL_LEVEL: 0
   CTEST_NO_TESTS_ACTION: error
   CMAKE_INSTALL_PREFIX: ~/libs
   CMAKE_PREFIX_PATH: ~/libs

on:
  push:
    paths:
      - "scripts/CMakeLists.txt"
      - "cmake/libraries.json"
      - ".github/workflows/ci_build.yml"

jobs:

  linux:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:

    - name: prereqs (Linux)
      if: runner.os == 'Linux'
      run: sudo apt install --no-install-recommends libopenmpi-dev

    - uses: actions/checkout@v4

    - name: Configure HDF5-MPI
      run: cmake -B build
      working-directory: scripts

    - name: Build/install HDF5
      run: cmake --build build
      working-directory: scripts

    - name: configure h5fortran
      run: cmake --preset default

    - name: build h5fortran
      run: cmake --build --preset default

    - name: test h5fortran
      run: ctest --preset default

    - name: install h5fortran
      run: cmake --install build

    - name: configure examples
      run: cmake --preset default
      working-directory: example

    - name: build Examples
      run: cmake --build --preset default
      working-directory: example

    - name: Test Examples
      run: ctest --preset default
      working-directory: example
